@startuml

class Camera
{
   cv::VideoCapture cameraUnit;

   Camera();
   cv::Mat getPhoto();
}

class Photo
{
   cv::Mat frame;
   float brightness;
   bool weather;
   int[2] sunPos, cloudPos;

   Photo();
   void setBrightness();
   void setWeather();
   void setSunPosition();
   void setCouldPosition();
}

class MainMachine
{
   Camera camera;
   Photo previousPhoto;
   Photo currentPhoto;
   
   MainMachine();
   void updatePhoto(camera);
   void calculateSpeed();
   void calculateTime();
   void uploadData();
   void switchGenerator();

   void start();
}

class Generator
{
   bool state;

   void switch();
}

class CloudStorage
{
  map<time_t, cv::Mat> data;

  void getData();
  cv::Mat sendData(time_t);
}

Camera -o MainMachine : has 1 <
Photo --o MainMachine : has 2 <
Camera - Photo
MainMachine - Generator : switches >
MainMachine -- CloudStorage : uploads data >
CloudStorage - User: uses <

@enduml
