@startuml

class Sun
{
   

}

class Camera
{
   cv::Mat getPhoto();
}

class Photo
{
   bool Weather

}

class MainMachine
{
   cv::Mat PreviousPhoto;
   cv::Mat CurrentPhoto;
   
   void updatePhoto();
   bool getDayTime();
   bool getWeather();
   void getPositions();
   void calculateSpeed();
   void calculateTime();
   void uploadData();
   void switchGenerator();

   void start();
}

class Generator
{
   bool state;

   void switch();
}

class CloudStorage
{
  map<time_t, cv::Mat> data;

  void getData();
  cv::Mat sendData(time_t);
}

Camera -o MainMachine : has 1 <
MainMachine - Generator : switches >
MainMachine -- CloudStorage : uploads data >
CloudStorage - User: uses <

@enduml
