@startuml

class Sun
{
   Position
}

class Cloud
{
   Position
}

class Sky
{
   Weather
}

class Photo
class Camera
class MainMachine

class Generator
{
   State
}

class CloudStorage
{
   AvailableSpace
}

Sky -- Photo : contains <
Photo -- Camera : makes <
Photo -- MainMachine: gets 2 <
Sun -- Sky : has 1 <
Sky - Cloud: owns several >
Camera - MainMachine : have 1 <
MainMachine - Generator : switches >
MainMachine -- CloudStorage : uploads data >
CloudStorage - User: gets data <

@enduml
