@startuml

class Sun
{
   Position
}

class Cloud
{
   Position
}

class Photo
{
   PixelMatrix
   Brightness
}
class Camera
class MainMachine
{
   Time
   CurrentWeather
}

class Generator
{
   State
}

class CloudStorage
{
   AvailableSpace
}

Photo -- Camera : makes <
Photo -- MainMachine: gets 2 <
Sun -- Photo : has 1 <
Photo - Cloud: has several >
Camera - MainMachine : has 1 <
MainMachine - Generator : switches >
MainMachine -- CloudStorage : uploads data >
CloudStorage - User: gets data <

@enduml
