@startuml

control "  main machine" as pc
entity "generator" as generator
actor "user" as user
database "  cloud\nstorage" as cloudStorage

(retrieve a photo) <- pc
(determine the time of day) <-- pc
(determine the weather) <-- pc
(determine the position of the sun and clouds) <-- pc
pc -> (calculate the speed and direction of clouds)
pc --> (turn the generator on/off)
pc --> (upload data to the cloud storage)
pc --> (calculate the time until the sun is not visible)

(turn the generator on/off) --> generator

(upload data to the cloud storage) --> cloudStorage
cloudStorage <-> user :data exchange

@enduml
