//Generator
@startuml
(*) --> [Start()] "STARTING"
"STARTING" --> [t = 10 secs] "AUTOMATIC"
"STARTING" --> "MANUAL"
"MANUAL" --> "ON"
"AUTOMATIC" --> "ON"
"ON" --> [Stop()] "STOPPING"
"STOPPING" --> [t = 10 secs] "OFF"
@enduml

//System
@startuml
(*) -->  [Turn on button] "STARTING"
"STARTING" --> [t = 10 secs] "ON"
"ON" ---> [Turn off button] "STOPPING"
"ON" --> [If sun will be closed soon] "START_GENERATOR"
"START_GENERATOR" --> "ON"
"ON" -> [If sun opened] "STOP_GENERATOR"
"STOP_GENERATOR" --> "ON"
"STOPPING" --> [t = 10 secs] "OFF"
@enduml
